# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
# https://docs.travis-ci.com/user/customizing-the-build/

language: python
python:
    - "3.6"

before_install:
  - sudo apt-get -qq update

# install - install any dependencies required
install:
    # install latest release version
    - wget $(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}')
    - sudo dpkg -i hugo*.deb
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo
    - echo 'luolvshi.me/hugo2' > public/CNAME

# deploy:
#  provider: pages
#  skip-cleanup: true
  # github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  email: edu@yuns.me
#  name: fydy
#  verbose: true
#  keep-history: true
#  local-dir: public
#  target_branch: master  # branch contains blog content
#  on:
#    branch: code  # branch contains Hugo generator code

after_script:
  - cd ./public
  - git init
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git add .
  - git commit -m "Update docs"
  - git push --quiet --force https://$code@github.com/fydy/hugo2.git master

notifications:
  email: false    # default notification method
  slack:
    rooms:
      secure: lVeyoBT074iOom//ugtS26TvAiLLpP73AT/g9JdsygL5ggNfrMgnyPqzkSzDkQye4imB8xTlYOuxZSlh9k3yqm4/aytI0+cCnrh8rrs/suZHU2LQL1gPEsUZEw4gDILIYDp4OsgiaAWXIKVXodJ49YdTTCQHf+0opzQKNHEpn2rhW/s+DoQPcZQOf7UnP/DELW10rrSFI9lx1K6RzVvLSi331URQswIf1R2drUcP+0dton+nFCufhtzaxew0b0qYD9a/ZVHcHQqHeFqRDqsr6gHMuu2ur+1Cl02m/FUwsVUEQY3kybcMOFFkNOup4VlForDB4xWFwIlF4u9Cy+Qe30mVb0SSioNxkPKOo1b+kbKdqT0WoYKUm2LeAzoL40uCcZWoZhI7ZPT6s/lkJIN3EG/AZtmd8NPZ4x3d5gk7+q0O/wXD/XVXiO2EU6R7mFzkFmJvaHSK1OtyBVC2QT4cXVSHgimGonCLC162J3tLXZsPcnySPnJ9YJX00yDDG2URtleFHaxyBsxsv/V9LdOB2nKpsctJuJsa6drO81Vf0ZBBVp+NyaoMobmWgVflvu6+lAMltbwgoExt26Gxreoqo7TOaT4wJdQpryl/AJMqIHjLf4+eHjNC2spGV4taim38OgadlYM5ttk6NvjqZzHIdc2LfZL6UKg/Poa1iryKJ3g=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo *%{repository_slug}* `%{result}` build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch *%{branch}*."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
